version: "3.9"
services:
  wedding:
    build: .
#    image: wedding-game:0.0.1-SNAPSHOT
    container_name: wedding-game
    environment:
      VIRTUAL_HOST: hochzeit.schuehly-it.de #Your Domain here
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: hochzeit.schuehly-it.de #Your Domain here
      LETSENCRYPT_EMAIL: thaiminater@outlook.com #Your Email
    env_file:
      - .env
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /root/tschuehly/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # LetsEncrypt plugin, which generates certificates
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=thaiminater@outlook.com
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
