spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  web:
    resources:
#      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: none
    default-schema: public
server:
  port: 80
  tomcat:
    max-http-form-post-size: 2000MB

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:datarecovery
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
  web:
    resources:
        static-locations: file:src/main/resources/static/
#logging:
#  level:
#    org.springframework.security: DEBUG
##log4j:
##  logger.org.hibernate:
##    SQL: DEBUG
##    type: TRACE
---
